service: tattoo

plugins:
  - serverless-iam-roles-per-function
  - serverless-pseudo-parameters
  - serverless-python-requirements
custom:
  stage: v1
  name:  tattoo
  tableThroughput: 2
  scannedTable: scannedTable--${self:custom.name}
  accountTable: accountTable--${self:custom.name}
  usersTable: usersTable--${self:custom.name}

provider:
  name: aws
  runtime: python3.6
  region: eu-west-1
  #Configure the bot by editing the env variables below
  environment:
    username: o_tattoo_0
    password: o_tattoo_08611
    rateLimitsFollow: 1000
    rateLimitsComment: 200
    rateLimitsLike: 200
    unfollowAll: 'False'
    tags: inkedman|inked4life|tattooaddict|tattoed|tattoosleeve|tattoedmen|inkedguy|inkedwomen|inkedlifestyle|tattoedman|inkedguys|tattooist|tattooart|tattooedgirls
    users: tattootattat|tattoodo|glorious_tattoo|best_tattoos_ig__|tattoo_collector
   
    scannedTable: scannedTable--${self:custom.name}
    accountTable: accountTable--${self:custom.name}
    usersTable: usersTable--${self:custom.name}

    next_max_id_queue: "https://sqs.eu-west-1.amazonaws.com/403838165554/nextMaxIdQueue"
    
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - arn:aws:dynamodb:${self:provider.region}:#{AWS::AccountId}:table/${self:custom.scannedTable}
        - arn:aws:dynamodb:${self:provider.region}:#{AWS::AccountId}:table/${self:custom.accountTable}
        - arn:aws:dynamodb:${self:provider.region}:#{AWS::AccountId}:table/${self:custom.usersTable}
    - Effect: Allow
      Action:
        - sqs:SendMessage
        - sqs:DeleteMessage
      Resource:
        - "arn:aws:sqs:${self:provider.region}:#{AWS::AccountId}:nextMaxIdQueue"

functions:

  analyze_followers:
    name: analyze_followers--${self:custom.name}
    handler: src/analyze_followers.analyze_followers
    events:
      - schedule: rate(8 hours)
      - sqs: "arn:aws:sqs:${self:provider.region}:#{AWS::AccountId}:nextMaxIdQueue"              
    timeout: 900 
    reservedConcurrency: 1
    memorySize: 128


  follow:
    name: follow--${self:custom.name}
    handler: src/follow.follow
    events:
          - schedule: rate(3 minutes)
    timeout: 10 
    reservedConcurrency: 0
    memorySize: 128
    
  unfollow:
    name: unfollow--${self:custom.name}
    handler: src/unfollow.unfollow
    events:
          - schedule: rate(3 minutes)
    timeout: 10 
    reservedConcurrency: 1
    memorySize: 128

  comment:
    name: comment--${self:custom.name}
    handler: src/comment.comment
    events:
          - schedule: rate(5 minutes)
    timeout: 10 
    reservedConcurrency: 1
    memorySize: 128

  like:
    name: like--${self:custom.name}
    handler: src/like.like
    events:
          - schedule: rate(5 minutes)
    timeout: 10 
    reservedConcurrency: 1
    memorySize: 128

  repost:
    name: repost--${self:custom.name}
    handler: src/repost.repost
    events:
          - schedule: rate(8 hours)
    timeout: 15 
    reservedConcurrency: 1
    memorySize: 128

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.usersTable}
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
          - AttributeName: pk
            AttributeType: N
        KeySchema:
          - AttributeName: username
            KeyType: HASH
          - AttributeName: pk
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: ${self:custom.tableThroughput}
          WriteCapacityUnits: ${self:custom.tableThroughput}

    scannedTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.scannedTable}
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
          - AttributeName: pk
            AttributeType: N
        KeySchema:
          - AttributeName: username
            KeyType: HASH
          - AttributeName: pk
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: ${self:custom.tableThroughput}
          WriteCapacityUnits: ${self:custom.tableThroughput}

    accountTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.accountTable}
        AttributeDefinitions:
          - AttributeName: date
            AttributeType: S
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: date
            KeyType: HASH
          - AttributeName: username
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: ${self:custom.tableThroughput}
          WriteCapacityUnits: ${self:custom.tableThroughput}

    nextMaxIdQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "nextMaxIdQueue"